version: 2
 jobs:
   build:
    working_directory: ~/app
     docker:
       - image: circleci/node:10
     steps:
       - checkout
       - restore_cache:
           keys:
             - dependency-cache-{{checksum "package.json"}}
             - dependency-cache-
       
       - run:
           name: Install All Dependencies
           command: yarn
           - save_cache:
            key: dependency-cache-{{checksum "package.json"}}
            paths:
              - node_modules
       - run:
           name: Build typescript
           command: yarn build:tsc
       - persist_to_workspace:
           root: .
           paths:
             - node_modules
             - dist
